### ISSUE TITLE
is kernel driver active error

### ISSUE THREAD

**Issue by taylorstevens** [benoitguigal/python-epson-printer#19]
I installed the software, but on passing my device id to the test script I hit this error:

~/python-epson-printer $ sudo python -m epson_printer.testpage -v 0x04b8 -p 0x0202
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/pi/python-epson-printer/epson_printer/testpage.py", line 14, in <module>
    printer = EpsonPrinter(options.id_vendor, options.id_product)
  File "epson_printer/epsonprinter.py", line 188, in __init__
    if self.printer.is_kernel_driver_active(0):
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 992, in is_kernel_driver_active
    interface)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/__init__.py", line 363, in is_kernel_driver_active
    _not_implemented(self.is_kernel_driver_active)
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/__init__.py", line 79, in _not_implemented
    raise NotImplementedError(func.__name__)
NotImplementedError: is_kernel_driver_active

I'm running this on Raspbian Wheezy on a rPi2. Is there anything I can do to fix this problem?

**Comment by benoitguigal** [comment]
Make sure your run pyusb version 1.0.0b1 as described here: 
https://github.com/arvydas/blinkstick-python/wiki/NotImplementedError-is_kernel_driver_active-on-some-Linux-systems

**Comment by taylorstevens** [comment]
This fixed the problem. Thank you!
